name: build
on: push

jobs:
  test-macOS:
    runs-on: macOS-11
    env:
      DEVELOPER_DIR: /Applications/Xcode_13.2.app/Contents/Developer
    steps:
      - uses: actions/checkout@v1.0.0
      - name: SwiftPM Build
        run: swift test
  test-iOS:
    runs-on: macOS-11
    env:
      DEVELOPER_DIR: /Applications/Xcode_13.2.app/Contents/Developer
    steps:
      - uses: actions/checkout@v1.0.0
      - name: xcodebuild
        run: |-
          xcodebuild \
            -scheme Buildkite \
            -destination "platform=iOS Simulator,OS=latest,name=iPhone 13 Pro" \
            -enableCodeCoverage YES \
            -quiet \
            build test
  test-linux:
    runs-on: ubuntu-latest
    container:
      image: swift:5.5
    steps:
      - uses: actions/checkout@v1.0.0
      - name: SwiftPM Build
        run: swift test
